// <auto-generated />
using System;
using Fiap.Api.EnvironmentalAlert.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Api.EnvironmentalAlert.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RM558332")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.EnvironmentalAlert.Model.ConsumptionAlertModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AlertAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ALERT_AT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DeviceId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DEVICE_ID");

                    b.Property<decimal?>("ExpectedLimit")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("EXPECTED_LIMIT");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("MESSAGE");

                    b.Property<decimal?>("RecordedConsumption")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("RECORDED_CONSUMPTION");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("CONSUMPTION_ALERT", "RM558332");
                });

            modelBuilder.Entity("Fiap.Api.EnvironmentalAlert.Model.DeviceConsumptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsumptionKwh")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("CONSUMPTION_KWH");

                    b.Property<int>("DeviceId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DEVICE_ID");

                    b.Property<decimal>("ExpectedLimitKwh")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("EXPECTED_LIMIT_KWH");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("RECORDED_AT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DEVICE_CONSUMPTION", "RM558332");
                });

            modelBuilder.Entity("Fiap.Api.EnvironmentalAlert.Model.DeviceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("LOCATION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("DEVICE", "RM558332");
                });

            modelBuilder.Entity("Fiap.Api.EnvironmentalAlert.Model.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ROLE");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.ToTable("USERS", "RM558332");
                });

            modelBuilder.Entity("Fiap.Api.EnvironmentalAlert.Model.ConsumptionAlertModel", b =>
                {
                    b.HasOne("Fiap.Api.EnvironmentalAlert.Model.DeviceModel", "Device")
                        .WithMany("ConsumptionAlerts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Fiap.Api.EnvironmentalAlert.Model.DeviceConsumptionModel", b =>
                {
                    b.HasOne("Fiap.Api.EnvironmentalAlert.Model.DeviceModel", "Device")
                        .WithMany("DeviceConsumptions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Fiap.Api.EnvironmentalAlert.Model.DeviceModel", b =>
                {
                    b.Navigation("ConsumptionAlerts");

                    b.Navigation("DeviceConsumptions");
                });
#pragma warning restore 612, 618
        }
    }
}
